name: Build Docker Image

on:
  repository_dispatch:
    types:
      - 'docker'

  workflow_dispatch:

jobs:
  run:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name: Build latest image
        run: docker buildx build --push -t marcorfilacarreras/repo-template:latest --platform linux/amd64,linux/arm64 .

      - name: Build commit image
        run: docker buildx build --push -t marcorfilacarreras/repo-template:${GITHUB_SHA::6} --platform linux/amd64,linux/arm64 .